export {actionTable1, actionTable2, descriptionTable1, descriptionTable2};

const actionTable1 = ["ATTAINMENT", "STARTING", "NEGLECT", "FIGHT", "RECRUIT", "TRIUMPH",
                      "VIOLATE", "OPPOSE", "MALICE", "COMMUNICATE", "PERSECUTE", "INCREASE",
                      "DECREASE", "ABANDON", "GRATIFY", "INQUIRE", "ANTAGONISE", "MOVE",
                      "WASTE", "TRUCE", "RELEASE", "BEFRIEND", "JUDGE", "DESERT", "DOMINATE",
                      "PROCRASTINATE", "PRAISE", "SEPARATE", "TAKE", "BREAK", "HEAL", "DELAY",
                      "STOP", "LIE", "RETURN", "IMMITATE", "STRUGGLE", "INFORM", "BESTOW",
                      "POSTPONE", "EXPOSE", "HAGGLE", "IMPRISON", "RELEASE", "CELEBRATE",
                      "DEVELOP", "TRAVEL", "BLOCK", "HARM", "DEBASE", "OVERINDULGE", "ADJOURN",
                      "ADVERSITY", "KILL", "DISRUPT", "USURP", "CREATE", "BETRAY", "AGREE",
                      "ABUSE", "OPPRESS", "INSPECT", "AMBUSH", "SPY", "ATTACH", "CARRY",
                      "OPEN", "CARELESSNESS", "RUIN", "EXTRAVAGANCE", "TRICK", "ARRIVE",
                      "PROPOSE", "DIVIDE", "REFUSE", "MISTRUST", "DECEIVE", "CRUELTY",
                      "INTOLERANCE", "TRUST", "EXCITEMENT", "ACTIVITY", "ASSIST", "CARE",
                      "NEGLIGENCE", "PASSION", "WORK HARD", "CONTROL", "ATTRACT", "FAILURE",
                      "PURSUE", "VENGEANCE", "PROCEEDINGS", "DISPUTE", "PUNISH", "GUIDE",
                      "TRANSFORM", "OVERTHROW", "OPPRESS", "CHANGE"];

const actionTable2 = ["GOALS", "DREAMS", "ENVIRONMENT", "OUTSIDE", "INSIDE", "REALITY",
                      "ALLIES", "ENEMIES", "EVIL", "GOOD", "EMOTIONS", "OPPOSITION", "WAR",
                      "PEACE", "THE INNOCENT", "LOVE", "THE SPIRITUAL", "THE INTELLECTUAL",
                      "NEW IDEAS", "JOY", "MESSAGES", "ENERGY", "BALANCE", "TENSION",
                      "FRIENDSHIP", "THE PHYSICAL", "A PROJECT", "PLEASURES", "PAIN",
                      "POSSESSIONS", "BENEFITS", "PLANS", "LIES", "EXPACTATIONS",
                      "LEGAL MATTERS", "BUREAUCRACY", "BUSINESS", "A PATH", "NEWS",
                      "EXTERIOR FACTORS", "ADVICE", "A PLOT", "COMPETITION", "PRISON",
                      "ILLNESS", "FOOD", "ATTENTION", "SUCCESS", "FAILURE", "TRAVEL",
                      "JEALOUSY", "DISPUTE", "HOME", "INVESTMENT", "SUFFERING", "WISHES",
                      "TACTICS", "STALEMATE", "RANDOMNESS", "MISFORTUNE", "DEATH",
                      "DISRUPTION", "POWER", "A BURDEN", "INTRIGUES", "FEARS", "AMBUSH",
                      "RUMOR", "WOUNDS", "EXTRAVAGANCE", "A REPRESENTATIVE", "ADVERSITIES",
                      "OPULENCE", "LIBERTY", "MILITARY", "THE MUNDANE", "TRIALS", "MASSES",
                      "VEHICLE", "ART", "VICTORY", "DISPUTE", "RICHES", "STATUS QUO",
                      "TECHNOLOGY", "HOPE", "MAGIC", "ILLUSIONS", "PORTALS", "DANGER",
                      "WEAPONS", "ANIMALS", "WEATHER", "ELEMENTS", "NATURE", "THE PUBLIC",
                      "LEADERSHIP", "FAME", "ANGER", "INFORMATION"];

const descriptionTable1 = ["ABNORMALLY", "ADVENTUROUSLY", "AGGRESSIVELY", "ANGRILY", "ANXIOUSLY",
                           "AWKWARDLY", "BEAUTIFULLY", "BLEAKLY", "BOLDLY", "BRAVELY", "BUSILY",
                           "CALMLY", "CAREFULLY", "CARELESSLY", "CAUTIOUSLY", "CEASELESSLY",
                           "CHEERFULLY", "COMBATIVELY",  "COOLLY", "CRAZILY", "CURIOUSLY",
                           "DAINTILY", "DANGEROUSLY", "DEFANTLY", "DELIBERATELY",
                           "DELIGHTFULLY", "DIMLY", "EFFCIENTLY", "ENERGETICALLY", "ENORMOUSLY",
                           "ENTHUSIASTICALLY", "EXCITEDLY", "FEARFULLY", "FEROCIOUSLY",
                           "FIERCELY", "FOOLISHLY", "FORTUNATELY", "FRANTICALLY", "FREELY",
                           "FRIGHTENINGLY", "FULLY", "GENEROUSLY", "GENTLY", "GLADLY",
                           "GRACEFULLY", "GRATEFULLY", "HAPPILY", "HASTILY", "HEALTHILY",
                           "HELPFULLY", "HELPLESSLY", "HOPELESSLY", "INNOCENTLY", "INTENSELY",
                           "INTERESTINGLY", "IRRITATINGLY", "JOVIALLY", "JOYFULLY",
                           "JUDGEMENTALLY", "KINDLY", "KOOKILY", "LAZILY", "LIGHTLY", "LOOSELY",
                           "LOUDLY", "LOVINGLY", "LOYALLY", "MAJESTICALLY", "MEANINGFULLY",
                           "MECHANICALLY", "MISERABLY", "MOCKINGLY", "MYSTERIOUSLY", "NATURALLY",
                           "NEATLY", "NICELY", "ODDLY", "OFFENSIVELY", "OFFCIALLY", "PARTIALLY",
                           "PEACEFULLY", "PERFECTLY", "PLAYFULLY", "POLITELY", "POSITIVELY",
                           "POWERFULLY", "QUAINTLY", "QUARRELSOMELY", "QUIETLY", "ROUGHLY",
                           "RUDELY", "RUTHLESSLY", "SLOWLY", "SOFTLY", "SWIFTLY", "THREATENINGLY",
                           "VERY", "VIOLENTLY", "WILDLY", "YIELDINGLY"];

const descriptionTable2 = ["ABANDONED", "ABNORMAL", "AMUSING", "ANCIENT", "AROMATIC", "AVERAGE",
                           "BEAUTIFUL", "BIZARRE", "CLASSY", "CLEAN", "COLD", "COLORFUL",
                           "CREEPY", "CUTE", "DAMAGED", "DARK", "DEFEATED", "DELICATE",
                           "DELIGHTFUL", "DIRTY", "DISAGREEABLE", "DISGUSTING", "DRAB", "DRY",
                           "DULL", "EMPTY", "ENORMOUS", "EXOTIC", "FADED", "FAMILIAR", "FANCY",
                           "FAT", "FEEBLE", "FEMININE", "FESTIVE", "FLAWLESS", "FRESH", "FULL",
                           "GLORIOUS", "GOOD", "GRACEFUL", "HARD", "HARSH", "HEALTHY", "HEAVY",
                           "HISTORICAL", "HORRIBLE", "IMPORTANT", "INTERESTING", "JUVENILE",
                           "LACKING", "LAME", "LARGE", "LAVISH", "LEAN", "LESS", "LETHAL",
                           "LONELY", "LOVELY", "MACABRE", "MAGNIFCENT", "MASCULINE", "MATURE",
                           "MESSY", "MIGHTY", "MILITARY", "MODERN", "EXTRAVAGANT", "MUNDANE",
                           "MYSTERIOUS", "NATURAL", "NONDESCRIPT", "ODD", "PALE", "PETITE",
                           "POOR", "POWERFUL", "QUAINT", "RARE", "REASSURING", "REMARKABLE",
                           "ROTTEN", "ROUGH", "RUINED", "RUSTIC", "SCARY", "SIMPLE", "SMALL",
                           "SMELLY", "SMOOTH", "SOFT", "STRONG", "TRANQUIL", "UGLY", "VALUABLE",
                           "WARLIKE", "WARM", "WATERY", "WEAK", "YOUNG"];
